Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -38,6 +38,17 @@ jobs:
         path: staging
         retention-days: 1
 
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    # - name: Update dependency graph
-    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+    - name: Find release and upload the JAR file
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        # Check if the release with tag 'test-tag' exists
+        release_id=$(gh release view test-tag --json id --jq ".id")
+
+        # If release exists, upload and overwrite the JAR file
+        if [ -n "$release_id" ]; then
+          gh release upload test-tag staging/*.jar --clobber
+        else
+          echo "Release with tag 'test-tag' not found."
+          exit 1
+        fi
